spring:
  main:
    banner-mode: "off"

# H2 databse configuration
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
  datasource:
    url: jdbc:h2:mem:challengedb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

# JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
